version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/medzudo/
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: scripts/deploy_laravel.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 120
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 120
      runas: root
